/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JFrame;
/**
 *
 * @author dfbaes
 */
public class PrincipalUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        initConfig();
    }
    
    private void initConfig(){
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("PRINCIPAL - TIENDITA DE DON PEPE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniClienteRegistro = new javax.swing.JMenuItem();
        mniClienteListar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniProductoRegistro = new javax.swing.JMenuItem();
        mniProductoListar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniVentaNueva = new javax.swing.JMenuItem();
        mniVentaHistorial = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mniReporteVenta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mniAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlDesktopLayout = new javax.swing.GroupLayout(pnlDesktop);
        pnlDesktop.setLayout(pnlDesktopLayout);
        pnlDesktopLayout.setHorizontalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        pnlDesktopLayout.setVerticalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        mniSalir.setText("Salir");
        jMenu1.add(mniSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        mniClienteRegistro.setText("Registro Cliente");
        jMenu2.add(mniClienteRegistro);

        mniClienteListar.setText("Listar Clientes");
        jMenu2.add(mniClienteListar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Productos");

        mniProductoRegistro.setText("Registro Producto");
        jMenu3.add(mniProductoRegistro);

        mniProductoListar.setText("Listar Productos");
        jMenu3.add(mniProductoListar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ventas");

        mniVentaNueva.setText("Nueva Venta");
        jMenu4.add(mniVentaNueva);

        mniVentaHistorial.setText("Historial Ventas");
        jMenu4.add(mniVentaHistorial);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        mniReporteVenta.setText("Reporte de Ventas");
        jMenu5.add(mniReporteVenta);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ayuda");

        mniAcercaDe.setText("Acerca de");
        jMenu6.add(mniAcercaDe);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniAcercaDe;
    private javax.swing.JMenuItem mniClienteListar;
    private javax.swing.JMenuItem mniClienteRegistro;
    private javax.swing.JMenuItem mniProductoListar;
    private javax.swing.JMenuItem mniProductoRegistro;
    private javax.swing.JMenuItem mniReporteVenta;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem mniVentaHistorial;
    private javax.swing.JMenuItem mniVentaNueva;
    private javax.swing.JDesktopPane pnlDesktop;
    // End of variables declaration//GEN-END:variables
}
